services:
    postgres:
        image: postgres:17
        container_name: jobtracker-postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 38utyf00p
            POSTGRES_DB: jobtracker
        ports:
          - "5432:5432"
        volumes:
          - "jobtracker_pgdata:/var/lib/postgresql/data"
volumes:
    jobtracker_pgdata: